---
resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource

resources:
- name: artifactory-repository
  type: artifactory
  check_every: 1m
  source:
    endpoint: http://((local_artifactory_ip)):8081/artifactory
    repository: "/example-repo-local"
    regex: test-agent_(?<version>.*).deb
    username: ((artifactory_user))
    password: ((artifactory_password))
- name: workspace-repo
  type: git
  source:
    uri: $TARGET_SOURCE_CODE_REPO
    branch: master
    private_key: ((publishing-outputs-private-key))

jobs:
  - name: job-test-build
    public: true
    plan:
      - get: workspace-repo
      - task: test-app-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: golang, tag: 1.14.15-stretch}
          inputs:
          - name: workspace-repo
          outputs:
          - name: workspace-repo-deb

          run:
            path: workspace-repo/hack/ci/local_build.sh

      - put: artifactory-repository
        params: { file: ./workspace-repo-deb/test-agent_*_amd64.deb } 
